### ISSUE TITLE
a button to reset gyro controls back to the start position

### ISSUE THREAD

**Issue by steventylerseanherr** [yuk27/BetterJoyForDolphin#1]
seeing as the last changes were 2 months ago
im sorry if i disturbed you
but could something like the gyro combo code be added to reset the gyro back to its starting position?
even if it was just a setting for the gyro combo code to reset it every time its triggered

**Comment by yuk27** [comment]
Hi @steventylerseanherr sorry for the late response. 
Please try with the latest version of BetterJoyForCemu (https://github.com/Davidobot/BetterJoy).
It has already implemented this request.

Let me know any follow-up questions.

Regards.

**Comment by UndarkAido** [comment]
@yuk27 Is BetterJoyForDolphin discontinued?
